
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
); 
//*******************************//

// add module here

logic clk;
freg_div_23 u_freg_div_23(
	.clk(CLK),
	.reset(~BTN[0]),
	.clk_out(clk)
);
logic [3:0]dd;
StudentID us(
    .clk(clk) , 
	.reset(~BTN[0]),
    .id(dd)
);
SevenDecoder useg(
	.A(dd),
	.seg(HEX0)
);

/*
logic clk;
freg_div_23 u_freg_div_23(
	.clk(CLK),
	.reset(~BTN[0]),
	.clk_out(clk)
);
logic [3:0]dd;
bir ubir(
	.clk(clk),
	.reset(~BTN[0]),
	.birth(dd)
);
SevenDecoder useg(
	.A(dd),
	.seg(HEX0)
);
*/



//*******************************//

endmodule
